### ISSUE TITLE
Redirect Url Issue

### ISSUE THREAD

**Issue by luisve1427** [auth0-samples/auth0-uwp-oidc-samples#16]
Issue Report
If you are reporting a bug, please fill the sections below (if they are applicable), otherwise feel free to delete those that don't apply. Thank you! 🙏🏼

Description
"Forbidden" error when trying to display login screen in UWP sample app

Expected behaviour
Login screen to be displayed

Actual behaviour
The screen does not show and forbidden error is returned

Steps to reproduce the problem
Download sample app, update to Auth0.OidcClient.UWP v3.1.2, run it.
Note that populating the app ms-app uri causes the login screen to display, but it does not return to the app afterwards. When I downgraded to version 2.4.3 returnUri is pre-populated and everything works as expected.

Language / Framework Versions
Language used: C#
Framework used: Microsoft.NETCore.UniversalWindowsPlatform v6.2.9
Testing environment
Operating system: Win10
Browser version: N/A
Screenshots
Feel free to insert here any screenshots that you consider helpful in solving your issue.

Filling this, you're helping yourself and repo maintainers in solving your issues quicker! Teamwork makes the dreamwork 🤜🏼🤛🏻

**Comment by frederikprijck** [comment]
Hi @luisve1427,

Sorry for the delayed reply. My guess it this is due to a misconfiguration on the Callback URL in Auth0. Apparantly our quickstart was not updated to align with `Auth0.OidcClient.UWP v3.1.2`.

Could you try and use the following callback URL in your Auth0 dashboard: `https://{AUTH0_DOMAIN}/mobile` (replace {AUTH0_DOMAIN} with your tenant's domain).

Let me know if that does or does not help.

**Comment by frederikprijck** [comment]
The quickstart has been updated.
